// src/app/pages/intake/constants.ts

export type IntakeStep = 1 | 2 | 3 | 4 | 5;

export const TAX_YEARS = [2025, 2024, 2023, 2022, 2021, 2020, 2019];

export const STEP_LABELS: Record<IntakeStep, string> = {
  1: 'LLC Details',
  2: 'Owner Details',
  3: 'Related Parties',
  4: 'Transactions',
  5: 'Review',
};

export const FILING_DUE_DATES: Record<
  number,
  { original: string; extended: string }
> = {
  2025: { original: '2026-04-15', extended: '2026-10-15' },
  2024: { original: '2025-04-15', extended: '2025-10-15' },
  2023: { original: '2024-04-15', extended: '2024-10-15' },
  2022: { original: '2023-04-15', extended: '2023-10-15' },
  2021: { original: '2022-04-15', extended: '2022-10-15' },
  2020: { original: '2021-04-15', extended: '2021-10-15' },
  2019: { original: '2020-04-15', extended: '2020-10-15' },
};

export type FilingTimingStatus = 'on_time' | 'within_extension' | 'delayed';

// TX_TYPES: category 1 = DIY-safe, 2 = may need CPA review, 3 = refer to CPA
// part: 'IV' | 'V' | 'VI'
export const TX_TYPES: {
  value: string;
  label: string;
  category: 1 | 2 | 3;
  part: 'IV' | 'V' | 'VI';
}[] = [
  // ── Part IV — Monetary transactions ──────────────────────────────────────
  {
    value: 'tangible_purchase',
    label: 'Purchase of tangible property',
    category: 1,
    part: 'IV',
  },
  {
    value: 'sales',
    label: 'Sales of goods / stock in trade',
    category: 2,
    part: 'IV',
  },
  {
    value: 'tangible_sale',
    label: 'Sale of tangible property',
    category: 2,
    part: 'IV',
  },
  {
    value: 'service_payment',
    label: 'Consideration for services',
    category: 2,
    part: 'IV',
  },
  {
    value: 'tech_services',
    label: 'Technical / managerial / scientific services',
    category: 2,
    part: 'IV',
  },
  { value: 'commission', label: 'Commission', category: 2, part: 'IV' },
  { value: 'rent', label: 'Rent', category: 2, part: 'IV' },
  { value: 'royalty', label: 'Royalty', category: 2, part: 'IV' },
  { value: 'interest', label: 'Interest', category: 2, part: 'IV' },
  {
    value: 'loan_to_llc',
    label: 'Loan to LLC (closing balance)',
    category: 2,
    part: 'IV',
  },
  {
    value: 'loan_from_llc',
    label: 'Loan from LLC (closing balance)',
    category: 2,
    part: 'IV',
  },
  {
    value: 'capital_contribution',
    label: 'Capital contribution',
    category: 2,
    part: 'IV',
  },
  { value: 'distribution', label: 'Distribution', category: 2, part: 'IV' },
  { value: 'dividend', label: 'Dividend', category: 2, part: 'IV' },
  {
    value: 'formation_costs',
    label: 'Formation costs (paid by owner)',
    category: 1,
    part: 'IV',
  },
  {
    value: 'intangible',
    label: 'Sale / lease / license of intangible property',
    category: 3,
    part: 'IV',
  },
  {
    value: 'platform_contribution',
    label: 'Platform contribution transaction (PCT)',
    category: 3,
    part: 'IV',
  },
  {
    value: 'cost_sharing',
    label: 'Cost sharing transaction',
    category: 3,
    part: 'IV',
  },
  {
    value: 'insurance',
    label: 'Insurance / reinsurance premium',
    category: 3,
    part: 'IV',
  },
  {
    value: 'loan_guarantee_fee',
    label: 'Loan guarantee fee',
    category: 3,
    part: 'IV',
  },
  { value: 'other', label: 'Other amount', category: 3, part: 'IV' },

  // ── Part V — Non-monetary / structural ───────────────────────────────────
  {
    value: 'formation_tx',
    label: 'Formation transaction',
    category: 1,
    part: 'V',
  },
  {
    value: 'dissolution_tx',
    label: 'Dissolution transaction',
    category: 2,
    part: 'V',
  },
  {
    value: 'acquisition_tx',
    label: 'Acquisition transaction',
    category: 3,
    part: 'V',
  },
  {
    value: 'disposition_tx',
    label: 'Disposition transaction',
    category: 3,
    part: 'V',
  },
  {
    value: 'other_part_v',
    label: 'Other Part V transaction',
    category: 3,
    part: 'V',
  },

  // ── Part VI — Nonmonetary / less-than-FMV ────────────────────────────────
  {
    value: 'nonmonetary_transfer',
    label: 'Nonmonetary transfer',
    category: 3,
    part: 'VI',
  },
  {
    value: 'less_than_fmv',
    label: 'Less-than-full-consideration transaction',
    category: 3,
    part: 'VI',
  },
  {
    value: 'property_transfer_fmv',
    label: 'Property transfer below FMV',
    category: 3,
    part: 'VI',
  },
  {
    value: 'other_part_vi',
    label: 'Other Part VI transaction',
    category: 3,
    part: 'VI',
  },
];

export const LOAN_TYPES = new Set([
  'loan_to_llc',
  'loan_from_llc',
  'capital_contribution',
  'distribution',
]);

export const ROYALTY_TYPES = new Set(['rent', 'royalty']);

export const PART_V_TYPES = new Set([
  'formation_tx',
  'dissolution_tx',
  'acquisition_tx',
  'disposition_tx',
  'other_part_v',
]);

export const PART_VI_TYPES = new Set([
  'nonmonetary_transfer',
  'less_than_fmv',
  'property_transfer_fmv',
  'other_part_vi',
]);

// ── rest of existing constants below (unchanged) ─────────────────────────

export const US_STATES: { value: string; label: string }[] = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'DC', label: 'Washington D.C.' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
  { value: 'PR', label: 'Puerto Rico' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
];

export const COUNTRIES: { value: string; label: string }[] = [
  { value: 'United States', label: 'United States' },
  { value: 'Afghanistan', label: 'Afghanistan' },
  { value: 'Albania', label: 'Albania' },
  { value: 'Algeria', label: 'Algeria' },
  { value: 'Andorra', label: 'Andorra' },
  { value: 'Angola', label: 'Angola' },
  { value: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Armenia', label: 'Armenia' },
  { value: 'Australia', label: 'Australia' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Azerbaijan', label: 'Azerbaijan' },
  { value: 'Bahamas', label: 'Bahamas' },
  { value: 'Bahrain', label: 'Bahrain' },
  { value: 'Bangladesh', label: 'Bangladesh' },
  { value: 'Barbados', label: 'Barbados' },
  { value: 'Belarus', label: 'Belarus' },
  { value: 'Belgium', label: 'Belgium' },
  { value: 'Belize', label: 'Belize' },
  { value: 'Benin', label: 'Benin' },
  { value: 'Bhutan', label: 'Bhutan' },
  { value: 'Bolivia', label: 'Bolivia' },
  { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
  { value: 'Botswana', label: 'Botswana' },
  { value: 'Brazil', label: 'Brazil' },
  { value: 'Brunei', label: 'Brunei' },
  { value: 'Bulgaria', label: 'Bulgaria' },
  { value: 'Burkina Faso', label: 'Burkina Faso' },
  { value: 'Burundi', label: 'Burundi' },
  { value: 'Cabo Verde', label: 'Cabo Verde' },
  { value: 'Cambodia', label: 'Cambodia' },
  { value: 'Cameroon', label: 'Cameroon' },
  { value: 'Canada', label: 'Canada' },
  { value: 'Central African Republic', label: 'Central African Republic' },
  { value: 'Chad', label: 'Chad' },
  { value: 'Chile', label: 'Chile' },
  { value: 'China', label: 'China' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Comoros', label: 'Comoros' },
  { value: 'Congo', label: 'Congo' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'Croatia', label: 'Croatia' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Cyprus', label: 'Cyprus' },
  { value: 'Czech Republic', label: 'Czech Republic' },
  { value: 'Denmark', label: 'Denmark' },
  { value: 'Djibouti', label: 'Djibouti' },
  { value: 'Dominica', label: 'Dominica' },
  { value: 'Dominican Republic', label: 'Dominican Republic' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'Egypt', label: 'Egypt' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
  { value: 'Eritrea', label: 'Eritrea' },
  { value: 'Estonia', label: 'Estonia' },
  { value: 'Eswatini', label: 'Eswatini' },
  { value: 'Ethiopia', label: 'Ethiopia' },
  { value: 'Fiji', label: 'Fiji' },
  { value: 'Finland', label: 'Finland' },
  { value: 'France', label: 'France' },
  { value: 'Gabon', label: 'Gabon' },
  { value: 'Gambia', label: 'Gambia' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Ghana', label: 'Ghana' },
  { value: 'Greece', label: 'Greece' },
  { value: 'Grenada', label: 'Grenada' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Guinea', label: 'Guinea' },
  { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
  { value: 'Guyana', label: 'Guyana' },
  { value: 'Haiti', label: 'Haiti' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Hungary', label: 'Hungary' },
  { value: 'Iceland', label: 'Iceland' },
  { value: 'India', label: 'India' },
  { value: 'Indonesia', label: 'Indonesia' },
  { value: 'Iran', label: 'Iran' },
  { value: 'Iraq', label: 'Iraq' },
  { value: 'Ireland', label: 'Ireland' },
  { value: 'Israel', label: 'Israel' },
  { value: 'Italy', label: 'Italy' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Jordan', label: 'Jordan' },
  { value: 'Kazakhstan', label: 'Kazakhstan' },
  { value: 'Kenya', label: 'Kenya' },
  { value: 'Kiribati', label: 'Kiribati' },
  { value: 'Kuwait', label: 'Kuwait' },
  { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
  { value: 'Laos', label: 'Laos' },
  { value: 'Latvia', label: 'Latvia' },
  { value: 'Lebanon', label: 'Lebanon' },
  { value: 'Lesotho', label: 'Lesotho' },
  { value: 'Liberia', label: 'Liberia' },
  { value: 'Libya', label: 'Libya' },
  { value: 'Liechtenstein', label: 'Liechtenstein' },
  { value: 'Lithuania', label: 'Lithuania' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Madagascar', label: 'Madagascar' },
  { value: 'Malawi', label: 'Malawi' },
  { value: 'Malaysia', label: 'Malaysia' },
  { value: 'Maldives', label: 'Maldives' },
  { value: 'Mali', label: 'Mali' },
  { value: 'Malta', label: 'Malta' },
  { value: 'Marshall Islands', label: 'Marshall Islands' },
  { value: 'Mauritania', label: 'Mauritania' },
  { value: 'Mauritius', label: 'Mauritius' },
  { value: 'Mexico', label: 'Mexico' },
  { value: 'Micronesia', label: 'Micronesia' },
  { value: 'Moldova', label: 'Moldova' },
  { value: 'Monaco', label: 'Monaco' },
  { value: 'Mongolia', label: 'Mongolia' },
  { value: 'Montenegro', label: 'Montenegro' },
  { value: 'Morocco', label: 'Morocco' },
  { value: 'Mozambique', label: 'Mozambique' },
  { value: 'Myanmar', label: 'Myanmar' },
  { value: 'Namibia', label: 'Namibia' },
  { value: 'Nauru', label: 'Nauru' },
  { value: 'Nepal', label: 'Nepal' },
  { value: 'Netherlands', label: 'Netherlands' },
  { value: 'New Zealand', label: 'New Zealand' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Niger', label: 'Niger' },
  { value: 'Nigeria', label: 'Nigeria' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Oman', label: 'Oman' },
  { value: 'Pakistan', label: 'Pakistan' },
  { value: 'Palau', label: 'Palau' },
  { value: 'Panama', label: 'Panama' },
  { value: 'Papua New Guinea', label: 'Papua New Guinea' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Peru', label: 'Peru' },
  { value: 'Philippines', label: 'Philippines' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Qatar', label: 'Qatar' },
  { value: 'Romania', label: 'Romania' },
  { value: 'Russia', label: 'Russia' },
  { value: 'Rwanda', label: 'Rwanda' },
  { value: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
  { value: 'Saint Lucia', label: 'Saint Lucia' },
  { value: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines' },
  { value: 'Samoa', label: 'Samoa' },
  { value: 'San Marino', label: 'San Marino' },
  { value: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia' },
  { value: 'Senegal', label: 'Senegal' },
  { value: 'Serbia', label: 'Serbia' },
  { value: 'Seychelles', label: 'Seychelles' },
  { value: 'Sierra Leone', label: 'Sierra Leone' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Slovakia', label: 'Slovakia' },
  { value: 'Slovenia', label: 'Slovenia' },
  { value: 'Solomon Islands', label: 'Solomon Islands' },
  { value: 'Somalia', label: 'Somalia' },
  { value: 'South Africa', label: 'South Africa' },
  { value: 'South Sudan', label: 'South Sudan' },
  { value: 'Spain', label: 'Spain' },
  { value: 'Sri Lanka', label: 'Sri Lanka' },
  { value: 'Sudan', label: 'Sudan' },
  { value: 'Suriname', label: 'Suriname' },
  { value: 'Sweden', label: 'Sweden' },
  { value: 'Switzerland', label: 'Switzerland' },
  { value: 'Syria', label: 'Syria' },
  { value: 'Taiwan', label: 'Taiwan' },
  { value: 'Tajikistan', label: 'Tajikistan' },
  { value: 'Tanzania', label: 'Tanzania' },
  { value: 'Thailand', label: 'Thailand' },
  { value: 'Timor-Leste', label: 'Timor-Leste' },
  { value: 'Togo', label: 'Togo' },
  { value: 'Tonga', label: 'Tonga' },
  { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
  { value: 'Tunisia', label: 'Tunisia' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'Turkmenistan', label: 'Turkmenistan' },
  { value: 'Tuvalu', label: 'Tuvalu' },
  { value: 'Uganda', label: 'Uganda' },
  { value: 'Ukraine', label: 'Ukraine' },
  { value: 'United Arab Emirates', label: 'United Arab Emirates' },
  { value: 'United Kingdom', label: 'United Kingdom' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Uzbekistan', label: 'Uzbekistan' },
  { value: 'Vanuatu', label: 'Vanuatu' },
  { value: 'Venezuela', label: 'Venezuela' },
  { value: 'Vietnam', label: 'Vietnam' },
  { value: 'Yemen', label: 'Yemen' },
  { value: 'Zambia', label: 'Zambia' },
  { value: 'Zimbabwe', label: 'Zimbabwe' },
];

export const BIZ_ACTIVITIES: { code: string; label: string }[] = [
  { code: '541511', label: 'Software Development' },
  { code: '513210', label: 'SaaS / Software Publisher' },
  { code: '541511', label: 'AI / Machine Learning Services' },
  { code: '541512', label: 'IT Consulting' },
  { code: '518210', label: 'Cloud / Hosting / DevOps' },
  { code: '541519', label: 'Cybersecurity' },
  { code: '541519', label: 'Data Analytics' },
  { code: '541611', label: 'Business Consulting' },
  { code: '541611', label: 'Management Consulting' },
  { code: '541613', label: 'Marketing Consulting' },
  { code: '541810', label: 'Digital Marketing Agency' },
  { code: '541430', label: 'Graphic Design' },
  { code: '541430', label: 'Web Design' },
  { code: '455219', label: 'Online Store (Shopify, WooCommerce, etc.)' },
  { code: '455219', label: 'Amazon FBA / Marketplace Seller' },
  { code: '425120', label: 'Import / Export' },
  { code: '423990', label: 'Wholesale Trade' },
  { code: '611420', label: 'Online Education / Courses' },
  { code: '561499', label: 'Business Support Services' },
  { code: '551112', label: 'Holding Company' },
  { code: '523999', label: 'Finance / Investment' },
  { code: '531390', label: 'Real Estate' },
  { code: '541990', label: 'Other Professional Services' },
];

export const RP_NAICS: { code: string; label: string; hint: string }[] = [
  {
    code: '541511',
    label: 'Software Developer / Programmer',
    hint: 'Freelance developers, agencies, AI engineers',
  },
  {
    code: '513210',
    label: 'SaaS Founder / Software Company',
    hint: 'SaaS startups, mobile apps',
  },
  {
    code: '541512',
    label: 'IT Consultant',
    hint: 'Technology consultants',
  },
  {
    code: '518210',
    label: 'Cloud / DevOps / Infrastructure',
    hint: 'Cloud engineers',
  },
  {
    code: '541519',
    label: 'Cybersecurity / Data / AI Services',
    hint: 'AI consultants, cybersecurity',
  },
  {
    code: '541611',
    label: 'Business Consultant',
    hint: 'General consulting',
  },
  {
    code: '541613',
    label: 'Marketing Consultant',
    hint: 'Marketing professionals',
  },
  {
    code: '541810',
    label: 'Digital Marketing Agency',
    hint: 'Advertising agencies',
  },
  {
    code: '541430',
    label: 'Graphic / UI-UX Designer',
    hint: 'Designers',
  },
  {
    code: '455219',
    label: 'E-commerce Seller',
    hint: 'Shopify, Amazon, Etsy',
  },
  {
    code: '425120',
    label: 'Import / Export Trader',
    hint: 'Trading businesses',
  },
  {
    code: '423990',
    label: 'Wholesale Business',
    hint: 'Product wholesalers',
  },
  {
    code: '611420',
    label: 'Online Education / Coach',
    hint: 'Coaches, course creators',
  },
  {
    code: '561499',
    label: 'Business Support Services',
    hint: 'VA agencies, outsourcing',
  },
  {
    code: '551112',
    label: 'Holding Company / Investor',
    hint: 'Investment holding companies',
  },
  {
    code: '523999',
    label: 'Finance / Investment',
    hint: 'Financial services',
  },
  {
    code: '531390',
    label: 'Real Estate',
    hint: 'Property-related businesses',
  },
  {
    code: '541990',
    label: 'Other Professional Services',
    hint: 'Catch-all for professionals',
  },
];
