/**
 * DownloadPackageButton
 *
 * Fetches a filing + its transactions from Supabase, generates
 * the Form 5472 and Pro Forma 1120 PDFs via pdf-lib, bundles
 * them into a ZIP (with optional Part V statement), and triggers
 * a browser download.
 *
 * pdf-lib and jszip are dynamically imported on first click so
 * they are excluded from the initial bundle (~529 kB saved).
 *
 * Usage:
 *   <DownloadPackageButton filingId="uuid" taxYear="2025" llcName="Acme LLC" />
 */

import { useState } from 'react';
import { Download, Loader2, FileText, CheckCircle2, AlertCircle } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { generateFilingPackage } from '../lib/pdfGenerator';
import type { Filing, Transaction } from '../lib/supabase';

interface Props {
  filingId: string;
  taxYear?: string;
  llcName?: string;
  /** Optional callback after successful generation */
  onSuccess?: () => void;
}

type Status = 'idle' | 'fetching' | 'generating' | 'bundling' | 'done' | 'error';

const STATUS_LABELS: Record<Status, string> = {
  idle:       'Download Filing Package',
  fetching:   'Loading filing data…',
  generating: 'Generating PDFs…',
  bundling:   'Creating ZIP…',
  done:       'Downloaded!',
  error:      'Failed — try again',
};

export function DownloadPackageButton({ filingId, taxYear, llcName, onSuccess }: Props) {
  const [status, setStatus] = useState<Status>('idle');
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  async function handleDownload() {
    if (status === 'fetching' || status === 'generating' || status === 'bundling') return;

    try {
      setStatus('fetching');
      setErrorMsg(null);

      // 1. Fetch filing row
      const { data: filingData, error: filingErr } = await supabase
        .from('filings')
        .select('*')
        .eq('id', filingId)
        .single();
      if (filingErr || !filingData) throw new Error(filingErr?.message ?? 'Filing not found');

      // 2. Fetch transactions for this filing
      const { data: txnsData, error: txnsErr } = await supabase
        .from('transactions')
        .select('*')
        .eq('filing_id', filingId);
      if (txnsErr) throw new Error(txnsErr.message);

      const filing = filingData as Filing;
      const transactions = (txnsData ?? []) as Transaction[];

      // 3. Generate PDF package
      setStatus('generating');
      const pkg = await generateFilingPackage(filing, transactions);

      // 4. Bundle into ZIP — lazy-load jszip only when needed
      setStatus('bundling');
      const { default: JSZip } = await import('jszip');
      const zip = new JSZip();
      const year = taxYear ?? filing.tax_year ?? String(new Date().getFullYear() - 1);
      const name = llcName ?? filing.llc_name ?? 'LLC';
      const slug = name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();

      zip.file(`Form_5472_${year}_${slug}.pdf`,       pkg.form5472Bytes);
      zip.file(`ProForma_1120_${year}_${slug}.pdf`,   pkg.proForma1120Bytes);

      if (pkg.hasPartV) {
        zip.file(
          `Form_5472_PartV_Statement_${year}_${slug}.txt`,
          pkg.partVStatement
        );
      }

      // README inside the ZIP
      zip.file('FILING_INSTRUCTIONS.txt', [
        `FORM 5472 FILING PACKAGE — TAX YEAR ${year}`,
        `Generated: ${new Date().toLocaleDateString('en-US')}`,
        '',
        'CONTENTS:',
        `  1. Form_5472_${year}_${slug}.pdf     — Completed Form 5472`,
        `  2. ProForma_1120_${year}_${slug}.pdf — Pro Forma Form 1120 (cover return)`,
        pkg.hasPartV
          ? `  3. Form_5472_PartV_Statement_${year}_${slug}.txt — Part V attachment`
          : '',
        '',
        'FILING INSTRUCTIONS:',
        '  - Attach Form 5472 to the Pro Forma Form 1120.',
        '  - Mail to: Department of the Treasury, Internal Revenue Service',
        '    Ogden, UT 84201-0012',
        '  - Due date: April 15 (or October 15 with Form 7004 extension).',
        '  - Penalty for late/incomplete filing: $25,000 per form (IRC § 6038A).',
        '',
        'This package was generated by your tax filing portal.',
        'Please review all fields with your CPA before filing.',
      ].filter(l => l !== '').join('\n'));

      const zipBlob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });

      // 5. Trigger download
      const url = URL.createObjectURL(zipBlob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `5472_filing_package_${year}_${slug}.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => URL.revokeObjectURL(url), 60_000);

      setStatus('done');
      onSuccess?.();

      // Reset to idle after 3s
      setTimeout(() => setStatus('idle'), 3000);

    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Unknown error';
      setErrorMsg(msg);
      setStatus('error');
      console.error('[DownloadPackageButton]', err);
    }
  }

  const isLoading = ['fetching', 'generating', 'bundling'].includes(status);

  return (
    <div className="flex flex-col gap-1">
      <button
        onClick={handleDownload}
        disabled={isLoading}
        className={[
          'inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium',
          'transition-all duration-150',
          status === 'done'
            ? 'bg-green-100 text-green-800 border border-green-200'
            : status === 'error'
            ? 'bg-red-100 text-red-800 border border-red-200'
            : isLoading
            ? 'bg-gray-100 text-gray-500 border border-gray-200 cursor-not-allowed'
            : 'bg-teal-600 text-white hover:bg-teal-700 border border-teal-600 cursor-pointer',
        ].join(' ')}
        aria-label={STATUS_LABELS[status]}
      >
        {isLoading ? (
          <Loader2 size={16} className="animate-spin" />
        ) : status === 'done' ? (
          <CheckCircle2 size={16} />
        ) : status === 'error' ? (
          <AlertCircle size={16} />
        ) : (
          <Download size={16} />
        )}
        <span>{STATUS_LABELS[status]}</span>
        {!isLoading && status === 'idle' && (
          <FileText size={14} className="opacity-60" />
        )}
      </button>

      {/* Progress hint during loading */}
      {isLoading && (
        <p className="text-xs text-gray-500 pl-1">
          {status === 'fetching' && 'Reading your filing data from database…'}
          {status === 'generating' && 'Filling IRS Form 5472 and Pro Forma 1120…'}
          {status === 'bundling' && 'Packaging PDFs into downloadable ZIP…'}
        </p>
      )}

      {/* Error detail */}
      {status === 'error' && errorMsg && (
        <p className="text-xs text-red-600 pl-1 max-w-xs">{errorMsg}</p>
      )}
    </div>
  );
}
