/**
 * copyPdfjsAssets - put pdf.js's standard font data where the browser can
 * fetch it.
 *
 *   node scripts/copyPdfjsAssets.mjs
 *
 * The draft preview rasterises the generated package in the browser. Our forms
 * draw their filled values with pdf-lib's StandardFonts (Helvetica and
 * Helvetica-Bold), which are base-14 fonts: the NAME is written into the PDF,
 * the glyphs are not. Every reader is expected to supply them.
 *
 * pdf.js supplies them from `standard_fonts/`, but only if it is told where to
 * fetch that from. Without it, it silently substitutes a fallback and the text
 * renders widely spaced and nothing like the printed page, which makes correct
 * output look broken. scripts/rasterSamplePreview.mjs hit exactly this in Node
 * and points at the directory on disk; the browser cannot, so the files are
 * copied into public/ instead.
 *
 * The copy is gitignored and regenerated by predev/prebuild, so it tracks
 * whatever pdfjs-dist version is installed rather than going stale in git.
 */
import { cp, mkdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');

const from = path.join(root, 'node_modules', 'pdfjs-dist', 'standard_fonts');
const to = path.join(root, 'public', 'pdfjs', 'standard_fonts');

if (!existsSync(from)) {
  // Not fatal: a build machine that has not installed dev dependencies should
  // still produce a site. The preview degrades to a readable-but-ugly raster
  // rather than taking the whole build down.
  console.warn('[copyPdfjsAssets] pdfjs-dist standard_fonts not found, skipping');
  process.exit(0);
}

await rm(to, { recursive: true, force: true });
await mkdir(path.dirname(to), { recursive: true });
await cp(from, to, { recursive: true });
console.log('[copyPdfjsAssets] copied standard_fonts to public/pdfjs/');
